export interface UniversitySuggestion {
  name: string;
  city: string;
  state: string;
  lat: number;
  lon: number;
  domain: string;
  school_type?: "Power" | "Mid-Major";
}

export const UNIVERSITIES: UniversitySuggestion[] = [
  { name: "Virginia Tech", city: "Blacksburg", state: "VA", lat: 37.2284, lon: -80.4234, domain: "vt.edu", school_type: "Power" },
  { name: "University of Virginia", city: "Charlottesville", state: "VA", lat: 38.0336, lon: -78.5080, domain: "virginia.edu", school_type: "Power" },
  { name: "University of Tennessee Knoxville", city: "Knoxville", state: "TN", lat: 35.9544, lon: -83.9243, domain: "utk.edu", school_type: "Power" },
  { name: "University of North Carolina Chapel Hill", city: "Chapel Hill", state: "NC", lat: 35.9049, lon: -79.0469, domain: "unc.edu", school_type: "Power" },
  { name: "University of Florida", city: "Gainesville", state: "FL", lat: 29.6436, lon: -82.3549, domain: "ufl.edu", school_type: "Power" },
  { name: "Arizona State University", city: "Tempe", state: "AZ", lat: 33.4242, lon: -111.9281, domain: "asu.edu", school_type: "Power" },
  { name: "University of Georgia", city: "Athens", state: "GA", lat: 33.9480, lon: -83.3774, domain: "uga.edu", school_type: "Power" },
  { name: "Clemson University", city: "Clemson", state: "SC", lat: 34.6834, lon: -82.8374, domain: "clemson.edu", school_type: "Power" },
  { name: "North Carolina State University", city: "Raleigh", state: "NC", lat: 35.7872, lon: -78.6672, domain: "ncsu.edu", school_type: "Power" },
  { name: "Boise State University", city: "Boise", state: "ID", lat: 43.6016, lon: -116.1995, domain: "boisestate.edu", school_type: "Mid-Major" },
  { name: "University of Alabama", city: "Tuscaloosa", state: "AL", lat: 33.2119, lon: -87.5444, domain: "ua.edu", school_type: "Power" },
  { name: "University of South Carolina", city: "Columbia", state: "SC", lat: 33.9963, lon: -81.0297, domain: "sc.edu", school_type: "Power" },
  { name: "Ohio State University", city: "Columbus", state: "OH", lat: 40.0076, lon: -83.0300, domain: "osu.edu", school_type: "Power" },
  { name: "Michigan State University", city: "East Lansing", state: "MI", lat: 42.7018, lon: -84.4822, domain: "msu.edu", school_type: "Power" },
  { name: "Texas A&M University", city: "College Station", state: "TX", lat: 30.6187, lon: -96.3365, domain: "tamu.edu", school_type: "Power" },
  { name: "Pennsylvania State University", city: "University Park", state: "PA", lat: 40.7982, lon: -77.8599, domain: "psu.edu", school_type: "Power" },
  { name: "Indiana University Bloomington", city: "Bloomington", state: "IN", lat: 39.1682, lon: -86.5230, domain: "indiana.edu", school_type: "Power" },
  { name: "University of Kentucky", city: "Lexington", state: "KY", lat: 38.0306, lon: -84.5037, domain: "uky.edu", school_type: "Power" },
  { name: "Mississippi State University", city: "Mississippi State", state: "MS", lat: 33.4554, lon: -88.7923, domain: "msstate.edu", school_type: "Power" },
  { name: "University of Nevada Las Vegas", city: "Las Vegas", state: "NV", lat: 36.1076, lon: -115.1405, domain: "unlv.edu", school_type: "Mid-Major" },
  { name: "University of Michigan", city: "Ann Arbor", state: "MI", lat: 42.2780, lon: -83.7382, domain: "umich.edu", school_type: "Power" },
  { name: "University of California Los Angeles", city: "Los Angeles", state: "CA", lat: 34.0689, lon: -118.4452, domain: "ucla.edu", school_type: "Power" },
  { name: "University of California Berkeley", city: "Berkeley", state: "CA", lat: 37.8724, lon: -122.2595, domain: "berkeley.edu", school_type: "Power" },
  { name: "University of Texas at Austin", city: "Austin", state: "TX", lat: 30.2849, lon: -97.7341, domain: "utexas.edu", school_type: "Power" },
  { name: "University of Washington", city: "Seattle", state: "WA", lat: 47.6553, lon: -122.3035, domain: "uw.edu", school_type: "Power" },
  { name: "University of Wisconsin Madison", city: "Madison", state: "WI", lat: 43.0766, lon: -89.4125, domain: "wisc.edu", school_type: "Power" },
  { name: "University of Illinois Urbana-Champaign", city: "Champaign", state: "IL", lat: 40.1020, lon: -88.2272, domain: "illinois.edu", school_type: "Power" },
  { name: "Purdue University", city: "West Lafayette", state: "IN", lat: 40.4259, lon: -86.9081, domain: "purdue.edu", school_type: "Power" },
  { name: "University of Minnesota", city: "Minneapolis", state: "MN", lat: 44.9740, lon: -93.2277, domain: "umn.edu", school_type: "Power" },
  { name: "University of Colorado Boulder", city: "Boulder", state: "CO", lat: 40.0076, lon: -105.2659, domain: "colorado.edu", school_type: "Power" },
  { name: "Colorado State University", city: "Fort Collins", state: "CO", lat: 40.5734, lon: -105.0865, domain: "colostate.edu", school_type: "Mid-Major" },
  { name: "Iowa State University", city: "Ames", state: "IA", lat: 42.0267, lon: -93.6465, domain: "iastate.edu", school_type: "Power" },
  { name: "Kansas State University", city: "Manhattan", state: "KS", lat: 39.1836, lon: -96.5717, domain: "ksu.edu", school_type: "Power" },
  { name: "University of Kansas", city: "Lawrence", state: "KS", lat: 38.9543, lon: -95.2558, domain: "ku.edu", school_type: "Power" },
  { name: "University of Missouri", city: "Columbia", state: "MO", lat: 38.9404, lon: -92.3277, domain: "missouri.edu", school_type: "Power" },
  { name: "University of Nebraska Lincoln", city: "Lincoln", state: "NE", lat: 40.8202, lon: -96.7005, domain: "unl.edu", school_type: "Power" },
  { name: "Oklahoma State University", city: "Stillwater", state: "OK", lat: 36.1156, lon: -97.0584, domain: "okstate.edu", school_type: "Power" },
  { name: "University of Oklahoma", city: "Norman", state: "OK", lat: 35.2059, lon: -97.4456, domain: "ou.edu", school_type: "Power" },
  { name: "University of Arkansas", city: "Fayetteville", state: "AR", lat: 36.0682, lon: -94.1742, domain: "uark.edu", school_type: "Power" },
  { name: "Louisiana State University", city: "Baton Rouge", state: "LA", lat: 30.4133, lon: -91.1800, domain: "lsu.edu", school_type: "Power" },
  { name: "Auburn University", city: "Auburn", state: "AL", lat: 32.6099, lon: -85.4808, domain: "auburn.edu", school_type: "Power" },
  { name: "University of Mississippi", city: "Oxford", state: "MS", lat: 34.3654, lon: -89.5378, domain: "olemiss.edu", school_type: "Power" },
  { name: "University of Memphis", city: "Memphis", state: "TN", lat: 35.1185, lon: -89.9374, domain: "memphis.edu", school_type: "Mid-Major" },
  { name: "University of Arizona", city: "Tucson", state: "AZ", lat: 32.2319, lon: -110.9501, domain: "arizona.edu", school_type: "Power" },
  { name: "New Mexico State University", city: "Las Cruces", state: "NM", lat: 32.2797, lon: -106.7481, domain: "nmsu.edu", school_type: "Mid-Major" },
  { name: "University of New Mexico", city: "Albuquerque", state: "NM", lat: 35.0844, lon: -106.6199, domain: "unm.edu", school_type: "Mid-Major" },
  { name: "University of Utah", city: "Salt Lake City", state: "UT", lat: 40.7649, lon: -111.8421, domain: "utah.edu", school_type: "Power" },
  { name: "Utah State University", city: "Logan", state: "UT", lat: 41.7458, lon: -111.8142, domain: "usu.edu", school_type: "Mid-Major" },
  { name: "University of Oregon", city: "Eugene", state: "OR", lat: 44.0459, lon: -123.0674, domain: "uoregon.edu", school_type: "Power" },
  { name: "Oregon State University", city: "Corvallis", state: "OR", lat: 44.5638, lon: -123.2794, domain: "oregonstate.edu", school_type: "Mid-Major" },
  { name: "Washington State University", city: "Pullman", state: "WA", lat: 46.7298, lon: -117.1817, domain: "wsu.edu", school_type: "Mid-Major" },
  { name: "Montana State University", city: "Bozeman", state: "MT", lat: 45.6669, lon: -111.0541, domain: "montana.edu", school_type: "Mid-Major" },
  { name: "University of Montana", city: "Missoula", state: "MT", lat: 46.8625, lon: -113.9848, domain: "umt.edu", school_type: "Mid-Major" },
  { name: "University of Wyoming", city: "Laramie", state: "WY", lat: 41.3149, lon: -105.5666, domain: "uwyo.edu", school_type: "Mid-Major" },
  { name: "University of Idaho", city: "Moscow", state: "ID", lat: 46.7271, lon: -116.9916, domain: "uidaho.edu", school_type: "Mid-Major" },
  { name: "University of South Florida", city: "Tampa", state: "FL", lat: 28.0587, lon: -82.4139, domain: "usf.edu", school_type: "Mid-Major" },
  { name: "Florida State University", city: "Tallahassee", state: "FL", lat: 30.4418, lon: -84.2985, domain: "fsu.edu", school_type: "Power" },
  { name: "University of Central Florida", city: "Orlando", state: "FL", lat: 28.6024, lon: -81.2001, domain: "ucf.edu", school_type: "Power" },
  { name: "Georgia Tech", city: "Atlanta", state: "GA", lat: 33.7756, lon: -84.3963, domain: "gatech.edu", school_type: "Power" },
  { name: "University of Maryland", city: "College Park", state: "MD", lat: 38.9869, lon: -76.9426, domain: "umd.edu", school_type: "Power" },
  { name: "Penn State University", city: "University Park", state: "PA", lat: 40.7982, lon: -77.8599, domain: "psu.edu", school_type: "Power" },
  { name: "Rutgers University", city: "New Brunswick", state: "NJ", lat: 40.5008, lon: -74.4474, domain: "rutgers.edu", school_type: "Power" },
  { name: "University of Pittsburgh", city: "Pittsburgh", state: "PA", lat: 40.4444, lon: -79.9608, domain: "pitt.edu", school_type: "Power" },
  { name: "Temple University", city: "Philadelphia", state: "PA", lat: 39.9812, lon: -75.1548, domain: "temple.edu", school_type: "Mid-Major" },
  { name: "University of Cincinnati", city: "Cincinnati", state: "OH", lat: 39.1329, lon: -84.5150, domain: "uc.edu", school_type: "Power" },
];
